### PR TITLE
v3.0.0

### LINKED ISSUE #718: [BUG] DEPRECATION WARNING: Rswag::Ui
## Describe the bug
In the first install, `config/initializers/rswag_ui.rb` generate old `swagger_endpoint`

```bash
DEPRECATION WARNING: Rswag::Ui: WARNING: The method will be renamed to "openapi_endpoint" in v3.0 (called from block in <main> at /config/initializers/rswag_ui.rb:11)
```

```ruby
Rswag::Ui.configure do |c|

  # List the Swagger endpoints that you want to be documented through the
  # swagger-ui. The first parameter is the path (absolute or relative to the UI
  # host) to the corresponding endpoint and the second is a title that will be
  # displayed in the document selector.
  # NOTE: If you're using rspec-api to expose Swagger files
  # (under openapi_root) as JSON or YAML endpoints, then the list below should
  # correspond to the relative paths for those endpoints.

  c.swagger_endpoint '/api-docs/v1/swagger.yaml', 'API V1 Docs'

  # Add Basic Auth in case your API is private
  # c.basic_auth_enabled = true
  # c.basic_auth_credentials 'username', 'password'
end
``` 

## Expected behavior
Create with:

```ruby
Rswag::Ui.configure do |c|

  # List the Swagger endpoints that you want to be documented through the
  # swagger-ui. The first parameter is the path (absolute or relative to the UI
  # host) to the corresponding endpoint and the second is a title that will be
  # displayed in the document selector.
  # NOTE: If you're using rspec-api to expose Swagger files
  # (under openapi_root) as JSON or YAML endpoints, then the list below should
  # correspond to the relative paths for those endpoints.

  c.openapi_endpoint '/api-docs/v1/swagger.yaml', 'API V1 Docs'

  # Add Basic Auth in case your API is private
  # c.basic_auth_enabled = true
  # c.basic_auth_credentials 'username', 'password'
end
```

## Additional context
No need rush, i dont know if there's someone fixing this.

## Dependency versions
The version of are you using for:
* Rswag:

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

### PR DESCRIPTION
**Pull request by romanblanco**
## Problem
PR to release changes for v3.0.0.

### This concerns this parts of the OpenAPI Specification:
* [v3.0.0](https://spec.openapis.org/oas/v3.0.0)
* [v3.1.0](https://spec.openapis.org/oas/v3.1.0)

### The changes I made are compatible with:
- [x] OAS3
- [x] OAS3.1

### Related Issues
- https://github.com/rswag/rswag/discussions/678

### Checklist
- [x] Added tests
- [x] Changelog updated
- [x] Added documentation to README.md
- [x] Added example of using the enhancement into [test-app](https://github.com/rswag/rswag/tree/master/test-app)

### CODE REVIEW

**Comment by romanblanco** [comment]
@jtannas @mattpolito @BookOfGreg, I've tried to [test](https://github.com/RedHatInsights/compliance-backend/compare/master...romanblanco:rswag-v3) the changes for v3.0.0 and they seem to work.

**Comment by philsturgeon** [comment]
I'll be happy to test this if you can shout when alpha version is tagged.

File: rswag-specs/lib/rswag/specs/request_factory.rb [hunk 1]
```diff
@@ -7,145 +7,120 @@
...
 
-      def build_query_string_part(param, value, swagger_doc)
+      def build_query_string_part(param, value, openapi_spec)
         name = param[:name]
         escaped_name = CGI.escape(name.to_s)
 
-        # OAS 3: https://swagger.io/docs/specification/serialization/
-        if swagger_doc && doc_version(swagger_doc).start_with?('3') && param[:schema]
+        # NOTE: https://swagger.io/docs/specification/serialization/
+        if param[:schema]
```
Comment (fynsta) [inline rswag-specs/lib/rswag/specs/request_factory.rb:124]: I can't add a comment down there, but shouldn't the `else` case be removed? Since it relies on `type` and `collectionFormat` which just do not exist anymore in the new OpenAPI version.

Comment (fynsta) [reply rswag-specs/lib/rswag/specs/request_factory.rb:124]: I also saw that RSwag explicitly supports using `type: ...` instead of the "correct" version`schema: { type: ... }`.  (in [this commit](https://github.com/rswag/rswag/commit/70eb277e049c95410aafb77807e227e4c85faebe)).

This actually leads to some confusing behaviour because in the current RSwag version: the only place where using `type: ` does not work is when trying to implement a specific serialization strategy (because then there is no `schema` key of course).

So I would move the
```
type = type = param[:type] || param.dig(:schema, :type)
```
to the top of the file instead, remove this condition altogether and then use that type for serialization.

File: rswag-api/lib/generators/rswag/api/install/templates/rswag_api.rb [hunk 2]
```diff
@@ -4,11 +4,11 @@
   # This is used by the Swagger middleware to serve requests for API descriptions
   # NOTE: If you're using rswag-specs to generate Swagger, you'll need to ensure
   # that it's configured to generate files in the same folder
-  c.openapi_root = Rails.root.to_s + '/swagger'
+  c.openapi_root = Rails.root.to_s + '/openapi'
```
Comment (BrianHawley) [inline rswag-api/lib/generators/rswag/api/install/templates/rswag_api.rb]: `Rails.root` is a Pathname, so it's better to do this:
```ruby
c.openapi_root = Rails.root.join('openapi').to_s
```

File: .github/workflows/ruby.yml [hunk 3]
```diff
@@ -11,18 +11,8 @@ jobs:
...
-        # excludes Rails 5.2.x on Ruby 3.0 and on 3.1 
-        # Note that 6.0.x should also exclude 3.0 and 3.1 but we're not testing it.
-        - rails: 5.2.6
-          ruby: 3.0
-        - rails: 5.2.6
-          ruby: 3.1
-        # Rails 7.0.1 requires >= 2.7.0, so excluding 2.6
-        - rails: 7.0.1
-          ruby: 2.6
+        ruby: [3.0, 3.1, 3.2] # 3.0 EOL is 2024-03-31
```
Comment (BrianHawley) [inline .github/workflows/ruby.yml]: Use "3.0" so it doesn't get converted to 3, which at this point would translate to 3.3. Also, add 3.3.

Comment (BrianHawley) [reply .github/workflows/ruby.yml]: At this point 3.0 was EOL way too recently, so it's probably a good idea to keep support for it.

File: rswag-specs/lib/rswag/specs/request_factory.rb (hunk 1 above)
Comment (romanblanco) [reply rswag-specs/lib/rswag/specs/request_factory.rb:124]: > https://github.com/rswag/rswag/pull/714/files#r1439746426

It can be removed. Thanks for pointing it out!

Comment (romanblanco) [reply rswag-specs/lib/rswag/specs/request_factory.rb:123]: > https://github.com/rswag/rswag/pull/714/files#r1439783378

I see `param[:schema][:type]` being handled in the case above:
https://github.com/rswag/rswag/blob/dc9c8bc894074295abad6afadfa4f0a8772c8b82/rswag-specs/lib/rswag/specs/request_factory.rb#L139

Correct me if I'm wrong, but it seems to me that the `type = type = param[:type] || param.dig(:schema, :type)` can be just removed

Comment (romanblanco) [reply rswag-specs/lib/rswag/specs/request_factory.rb:124]: Reminder to handle invalid attributes:

https://github.com/rswag/rswag/commit/812d311426c323c76d32ee7fdb17931d7f98f565#r148058990

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,6 +4,24 @@ All notable changes to this project will be documented in this file.
...
+
+- Dropped using #send (https://github.com/rswag/rswag/pull/396)
+
+### Added
+
+### Changed
+
+- Drop support for OpenAPI v2 (Swagger) (https://github.com/rswag/rswag/pull/574)
+- Drop Rspec V2 support (https://github.com/rswag/rswag/pull/636)
+- upgrade to ruby 3.0.6 and rails 7.0.4.3 in local dev (https://github.com/rswag/rswag/pull/625)
```
Comment (jtannas) [inline CHANGELOG.md:19]: Let's make a note about dropping official support for Ruby 2.7 in this release.
I'd like to start using endless methods to help tidy up.

P.S. Hash literal omission from Ruby 3.1 would also be nice but 3.0 isn't EOL until 2 months from now.

**Review by jtannas — APPROVED** [review]
I don't have much to say about the v3 changes so far since it's I'm just getting back into the project.
I'm eager to get them into `master` though since I'd like to build on them for a more extensive project revamp.

ie. [my notes](https://fish-locket-90a.notion.site/RSwag-Notes-18b2f8f8fc4d806ab67df592f8cc7b3f)

Hopefully that happens soon :crossed_fingers:

**Comment by romanblanco** [comment]
> I'll be happy to test this if you can shout when alpha version is tagged.

@philsturgeon, thank you for offering your help!

The pre-release is now out: https://github.com/rswag/rswag/releases/tag/3.0.0.pre

**Comment by philsturgeon** [comment]
@romanblanco congratulations! Massive effort! 

Getting from 3.0 to 3.1 was not super simple, but hopefully getting to 3.2 will be no effort at all in comparison: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.2.0
